sh

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,23 +1,30 @@
-#!/bin/bash
+#!/usr/bin/env bash
 
-# Check if all required parameters are provided
-if [ "$#" -lt 4 ]; then
+# Function to display usage
+display_usage() {
     echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+}
+
+# Check if number of arguments is less than 4
+if [ "$#" -lt 4 ]; then
+    display_usage
     exit 1
 fi
 
 # Assign parameters to variables
-file_path="$1"
-server_ip="$2"
-username="$3"
-ssh_key="$4"
+FILE_PATH="$1"
+SERVER_IP="$2"
+USERNAME="$3"
+SSH_KEY="$4"
 
-# Transfer the file using scp
-scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
-
-# Check if scp command was successful
-if [ "$?" -eq 0 ]; then
-    echo "File transfer completed successfully."
-else
-    echo "File transfer failed."
+# Check if file exists
+if [ ! -f "$FILE_PATH" ]; then
+    echo "Error: File '$FILE_PATH' does not exist."
+    exit 1
 fi
+
+# Transfer file using scp
+scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$FILE_PATH" "$USERNAME@$SERVER_IP":~/ && \
+echo "File transferred successfully to $USERNAME@$SERVER_IP:~/" || \
+echo "Failed to transfer file to $USERNAME@$SERVER_IP:~/"
+
